cloud:
  aws:
    credentials:
      access-key: AKIAU2ZC5LHJ4FWUYPGG
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: multirestaurante-images


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

